### ISSUE TITLE
Using ibm.power_ibmi.ibmi_copy module results in a warning message

### ISSUE THREAD

**Issue by krka01** [IBM/ansible-for-i#146]
Environment: ibm.power_ibmi collection version 1.9.0 runing on ansible [core 2.12.6]

Using the ibm.power_ibmi.ibmi_copy module results in the following warning:

[DEPRECATION WARNING]: The '_remote_checksum()' method is deprecated. The plugin author should update the code to use '_execute_remote_stat()' instead. This feature will be removed 
in version 2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by krka01** [comment]
Is there any work ongoing with this issue?

The  ibm.power_ibmi.ibmi_copy module are using the '_remote_checksum()' method and the method will be removed in ansible core version 2.16

ansible core version 2.16 were released  06 Nov 2023 and are considered the current version
Ref: https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html

I was hoping this should been fixed in the new power ibm i collection 1.9.2 that were released a few days ago.

**Comment by robgjertsen1** [comment]
I'll keep this in mind with next drop after 2.0.0 and see if I can fix it there. I've had to focus on getting collection up to ansible core 2.14 and 2.15 and ansible lint production mode code clean-up for continued Redhat collection certification with release of 2.0.0. And there is still more to do with ansible lint code clean up for follow on release to 2.0.0.

**Comment by hsjodin-ibm** [comment]
Hi i have got a new mac  and a got ansible 2.16.2 installd i cant find how to go back to 2.15...  and now me ibm_script not working
FAILED! => {"changed": false, "delta": "", "job_log": [], "rc": 255, "stderr": "'ActionModule' object has no attribute '_remote_checksum'", "stderr_lines": "", "stdout": "", "stdout_lines": ""}.
please urgent fix needed or workaround

**Comment by robgjertsen1** [comment]
You'll need to roll back to 2.15 for now. Unfortunately I don't use a mac, so can't help in that area. Easiest way around is probably to create a python virtual environment and use pip to install an older version of ansible in that environment.

**Comment by hsjodin-ibm** [comment]
Okay, tanks. Do you have a ETA on when it can work in 2.16

**Comment by robgjertsen1** [comment]
Hopefully by March / April time frame.

**Comment by robgjertsen1** [comment]
Fixed with 2.0.1 release.
